[pytest]
# Automatically treat all async test functions as asyncio tests
asyncio_mode = auto

pythonpath = .

# Sets the default scope for async fixtures to avoid deprecation warnings
asyncio_default_fixture_loop_scope = function

# Defines where pytest should look for tests
testpaths = tests

# Optional: Add custom markers if you want to group tests later
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')